### PR TITLE
Update build notes

### PR DESCRIPTION
**Pull request by joniles**
Provide details of prerequisites for a working build.

### CODE REVIEW

**Comment by wasabii** [comment]
Wow, thanks man. Good to see somebody working on cleaning some of this up.

You added a note about the source directory. The IKVM git repository actually includes it as a submodule. So as long as you make sure to checkout submodules too, you'll be fine. Still need the build, though.

**Comment by joniles** [comment]
Thanks for the feedback, I'll update the notes to deal with the using the submodule.

**Comment by bogatykh** [comment]
About clang - you can use Visual Studio included CLANG + LLVM. Add PATH env variable after that: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin

See:
https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170

**Comment by wasabii** [comment]
> About clang - you can use Visual Studio included CLANG + LLVM. Add PATH env variable after that: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
> 
> See: https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170



> About clang - you can use Visual Studio included CLANG + LLVM. Add PATH env variable after that: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
> 
> See: https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170

My experience was the version was out of date.

**Comment by bogatykh** [comment]
> > About clang - you can use Visual Studio included CLANG + LLVM. Add PATH env variable after that: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
> > See: https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170
> 
> > About clang - you can use Visual Studio included CLANG + LLVM. Add PATH env variable after that: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
> > See: https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170
> 
> My experience was the version was out of date.

I have just installed Clang + LLVM included in Visual Studio 2022 and everything compiled successfully.

**Pull request merged**
